### ISSUE TITLE
No web UI visible

### ISSUE THREAD

**Issue by bfonn** [LiNgOtT/raspberry-pi-cistern-gauge-level#2]
I appreciate that this has not been looked at for some time now, but any chance you could help me get this up and running? Im unable to get this showing when directing browser to IP. Also tried adding it with a new web root folder, but doesnt display, just shows a list with the folder content

Running on RPi 3 B+ APACHE2 PHP7.0

**Comment by LiNgOtT** [comment]
Great to hear that you want to use my project. 

Regarding your issue, I think your Apache is not configured correctly.
Check out the documentation of the [DirectoryIndex](https://httpd.apache.org/docs/2.4/mod/mod_dir.html#directoryindex). 
Please check that you have enabled _Apache mod_dir_.

**Comment by bfonn** [comment]
Thank you for the response. I have tried to play around with it some more,
and i cant quite figure it out.
So, i have added this to the VirtualHost file; (renamed the
raspberry-pi-cistern-gauge-level folder to "well")
<Directory /var/www/html/well/web>
        DirectoryIndex app.php
        AllowOverride All
        </Directory>

But it doesnt seem to work. I im presented with a blank page.

Here are the tings ive done.
Reinstalled Rasbian Stretch - full version
Installed php7.3
Installed Apache2
Enabled rewrite module
cloned your project to /var/www/html/ (and renamed the folder "well)
executed the $ composer update
and got a completed message at the end.

created a test.php and added this file to the DirectoryIndex test.php
this works

So, any other suggestions or tips i might have missed?

Any help would be appreciated :)

Best regards,
Bjørnar Fonn

**Comment by LiNgOtT** [comment]
Could be a php7 issue.
Please check your php error logs.
The code was designed to work with php5.

I have updated composer.json file so that php7 does not satisfy the requirement.

**Comment by bfonn** [comment]
Tried purging the 7.3 and installing 5.6
did a fresh composer update
still the same.

I dont know how to troubleshoot this issue. Do you have a copy of a working
VirtualHost file so i can compare to mine?

I really wanted this to work, as i need some sort of monitoring sw at our
cabin, and this ticked all the boxes for me :)

**Comment by LiNgOtT** [comment]
Please check your php error logs.
I think the white page is caused by a fatal error.
